### PR TITLE
Fix 18CO Closed companies being available for purchase

### PR DESCRIPTION
**Pull request by ryandriskel**
Fix https://github.com/tobymao/18xx/issues/2996

This will break games because passes turn into skips. Suggest merge at the same time as https://github.com/tobymao/18xx/pull/2936

### CODE REVIEW

**Comment by ryandriskel** [comment]
It appears this may have occurred within my fixture. I'll need to get a new one, sigh.

**Comment by jenf** [comment]
should be easy to change migrate_game to cope with this.

**Comment by ryandriskel** [comment]
Moving to Draft while I learn migrate_game

**Comment by ryandriskel** [comment]
> should be easy to change migrate_game to cope with this.

The updated fixture was generated by running the migration against the fixture. :)

**Review by tobymao — APPROVED** [review]

**Pull request merged**
