### PR TITLE
18Texas: remove use of on_phase in abilities

### LINKED ISSUE #6700: 18Texas IGN private/blocked hexes--unable to lay
Game 66785
https://18xx.games/game/66785

I hold IGN and presidency of currently operating company.  It is phase 3.  When I attempt to lay D3, I get message, "D3 is blocked by International-Great Northern."  I have verified that I should be able to place tiles in the blocked hexes, and there does not seem to be a way to do this.

Browser is Firefox version 95.0 (64 bit).

Thanks!

DK

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #6700

### CODE REVIEW

**Comment by discoking7** [comment]
This remains a problem in game 66785.
https://18xx.games/game/66785

**Comment by tobymao** [comment]
@discoking7 you have to check what is deployed

**Comment by scottredracecar** [comment]
Looks like it works now.

**Comment by scottredracecar** [comment]
@discoking7 just because it is merged, doesn't mean it is live on the site yet, you have to check the about page to see what the latest commit that was deployed is.
https://18xx.games/about

**Comment by discoking7** [comment]
Sorry guys...I'm unfamiliar with GitHub and this terminology, so I didn't know what to do when the thread disappeared from the home page.  I see that the fix is in, and the game has progressed.  Thanks!

**Pull request merged**
