### PR TITLE
Added a new "Import game" option in new_game

### PR DESCRIPTION
**Pull request by daniel-sousa-me**
Added a new "Import game" option in new_game and move the json textarea from hotseat

### CODE REVIEW

**Comment by tobymao** [comment]
what's the point of this pr?

**Comment by daniel-sousa-me** [comment]
Just better ux. Trying to keep things more organised and clear

**Comment by tobymao** [comment]
can you show me a picture of before and after?

**Comment by daniel-sousa-me** [comment]
The current version:

new_game_old

Both views on my proposal:

new_game_hotseat

new_game_import

Maybe I'd also make the textarea smaller. I don't think anybody will read the json x)
And usually the user can make it bigger by dragging the corner

**Comment by ryandriskel** [comment]
I see the idea. You use either the config OR the json, never both at the same time, so it is a little awkward to have them both on the same interface.

I feel the new radio looks a little cluttered. Maybe "Import Hotseat" instead of "Import game (hotseat)" ?

**Comment by tobymao** [comment]
can you fix the merge conflict?

**Comment by michaeljb** [comment]
I got the merge conflict fixed; this was conflicting with changes I had made in #1930

**Review by michaeljb — APPROVED** [review]

**Pull request merged**
