### PR TITLE
1870: St. Louis was losing the P label when the private was used

### PR DESCRIPTION
**Pull request by daniel-sousa-me**

### CODE REVIEW

**Comment by daniel-sousa-me** [comment]
When this is merged, I'll add a fixture with a real game (which now fails)

**Comment by daniel-sousa-me** [comment]
This will archive some games

**Comment by jenf** [comment]
Is this in reference to a bug? Is it upgradable tiles that get the label added? If so, that will cause problems as the tile will retain the label after being upgraded

**Comment by daniel-sousa-me** [comment]
The label is being added and removed on step/track, but I forgot to add here. There's no need to remove on the special track, because there's no ability allowing upgrades

**Review by jenf — APPROVED** [review]

**Pull request merged**
