### PR TITLE
Purple navbar when in hotseat mode

### PR DESCRIPTION
**Pull request by ventusignis**
Fixes https://github.com/tobymao/18xx/issues/2167
I still want to take time to get a 2p non-hotseat game going in my local to verify that this doesn't break anything and adding hotseat to the text somewhere would probably be warranted too

### CODE REVIEW

**Comment by ventusignis** [comment]
image
I chose a shade of purple because it is roughly opposite of orange. I am open to suggestions for a different default

**Comment by ventusignis** [comment]
image

**Comment by tobymao** [comment]
sure, i don't mind

**Comment by daniel-sousa-me** [comment]
> adding hotseat to the text somewhere would probably be warranted too

Let's replace the logo with a flaming chair!

**Comment by ryandriskel** [comment]
Ventu - any reason to keep holdng this?

**Comment by tobymao** [comment]
closing for now

**Comment by ventusignis** [comment]
@ryandriskel 2 reasons - 1: I was focusing what energy I had on 1856 so I never got around to testing a live game locally to make sure this didn't break normal games and 2: I want to also put a [Hotseat] label before the game name in the game action / status bar

**Pull request closed without merging**
