### PR TITLE
[rolling stock] fix broken dividend step

### LINKED ISSUE #9888: [Rolling Stock Stars] dividend step throws error
**Game ID**
138858

https://gist.github.com/benjaminxscott/063ba50d1a4c376838f4eb794d2506f0

**Link**
https://18xx.games/game/138858

**How to Reproduce the Bug?**
Due to the behavior described in the title, I'm not in a position to contribute any further information.

During Turn 6, closing everything went well.  Currently it's my turn for dividends (T6).

**Which Browser / Platform?**

Checked on:
- Chrome Version 119.0.6045.124
- MS Edge Version 119.0.2151.44

### PR DESCRIPTION
**Pull request by benjaminxscott**
Fixes #9888

### Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [NA] Add the `pins` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### Implementation Notes

* **Explanation of Change**

Rolling stock's dividend step used to inherit from base.rb instead of base/dividend.rb, for some reason

Also adds a test file

* **Screenshots**

* **Any Assumptions / Hacks**

### CODE REVIEW

**Comment by roseundy** [comment]
Why are you changing this?

**Comment by roseundy** [comment]
If the only reason you are inheriting from Dividend is to define 'variable_share_multiplier', why don't you just define it?

**Comment by benjaminxscott** [comment]
I don't have a strong preference for implementation, it seems like this step is handling dividends so it seemsodd to have it derive from the base step instead

**Comment by benjaminxscott** [comment]
As mentioned in a (deleted?) comment, we could define `variable_share_multiplier` explicitly, which is also fine, I don't have a preference for either approach

**Comment by roseundy** [comment]
That would be my preferred approach, but why this is failing now? I deleted my comment because I saw you already added variable_share_multiple to Rolling Stock in a previous PR (#9827)

**Comment by benjaminxscott** [comment]
no worries, it was my bad -not sure why the tests didn't catch it?

**Comment by roseundy** [comment]
LGTM

**Pull request merged**
