### PR TITLE
WIP: Attempt to keep trains for IR's out of market

### PR DESCRIPTION
**Pull request by gchambers419**
First attempt to keep the trains for Big 4 and Michigan Southern out of the market.

Not yet tested; will do so after work ~7EDT

### CODE REVIEW

**Comment by jenf** [comment]
Generally, I don't think we're changing the config file since that comes from 18xx maker.

We should implement a way of disabling trains going into the discard (also needed for 1882), and when those privates get the trains marking them as such.

**Comment by gchambers419** [comment]
If this works, the next step is to work out patches for 18xx-maker and export-rb, but I see your point.

**Comment by jenf** [comment]
Fair enough :)

**Comment by tobymao** [comment]
we won’t be doing it like this, it will be a code change

**Pull request closed without merging**
