### PR TITLE
1877 Add mine tiles

### PR DESCRIPTION
**Pull request by scottredracecar**

### CODE REVIEW

**Comment by michaeljb** [comment]
Fixed the merge conflict from using the new game file structure, but last I asked, sounded like the jury was still out on whether this should be merged in? @tobymao

**Comment by tobymao** [comment]
this needs some game changes to actually work, because it requires rantdomized setup

**Comment by CaptainObi** [comment]
@tobymao I implemented some random setup in the 18USA initial PR.[Here]( https://github.com/tobymao/18xx/commit/b856969e68b10eaa856fef07135eb4fa7ae268f9#diff-439b759173e839d5749b4c8ac85c533b1c06d2b961234f86afce2b135e799c01). It basically randomizes offboard values but randomizing other things shouldn't be too hard.

**Comment by tobymao** [comment]
closing this for now may pick up later

**Pull request closed without merging**
