### PR TITLE
1870: Change corporation colors so that they are closer to the print version

### PR DESCRIPTION
**Pull request by daniel-sousa-me**

### CODE REVIEW

**Comment by jenf** [comment]
You'd need to add it to the color map as well... however, note that the code is presently frozen as we're trying to remove the json files. When it's done resubmit this once we've migrated.

**Comment by daniel-sousa-me** [comment]
Aren't those just CSS colors?

**Comment by jenf** [comment]
partially, but we generally replace them with the rgb in case we need to do math

**Comment by daniel-sousa-me** [comment]
Ok, I'll redo this with more standard colors, then x)

**Comment by jenf** [comment]
you can add whatever colours you want, just needs to add them to the mapping

**Pull request closed without merging**
