### PR TITLE
Removed a visual error with limited train buying in 18AL (fixes #1625)

### LINKED ISSUE #1625: 18AL: Misleading label on info screen
On the Info screen for 18AL, Phase 4 is labeled with "Limited Train Buy".  However, the rules (and the implementation) specifically permit multiple buys as soon as the first 4 train is bought. (4.2.5.f)

### PR DESCRIPTION
**Pull request by CaptainObi**
The info table for 18al no longer shows limited train buy as a status for 4 trains

### CODE REVIEW

**Review by perwestling — CHANGES_REQUESTED** [review]
Change is fine but you need to fix up your commits. 
It is 21 commits but it just need one. So you need a master or branch that is that same as tobymao/18xx on which you apply your change for this commit.
Try to clean up your commits/branches before pushing them.

**Comment by perwestling** [comment]
@CaptainObi  If you check commit tab of this PR it looks like this:
image

Compare this to the other current PRs or one of the closed ones.

**Comment by CaptainObi** [comment]
> 
> 
> Change is fine but you need to fix up your commits.
> It is 21 commits but it just need one. So you need a master or branch that is that same as tobymao/18xx on which you apply your change for this commit.
> Try to clean up your commits/branches before pushing them.

How exactally should I do this? I've tried to rebase before sumbiting a PR, it doesn't seem to work

**Comment by yzemaze** [comment]
If you don’t know anything about git, it’s about time you learn at least the basics and some useful concepts along the way. There are plenty tutorials and search engines available.

**Comment by dfannius** [comment]
It looks like you are doing all your work on your master branch. That's a recipe for trouble. [This page](https://gist.github.com/Chaser324/ce0505fbed06b947d962) looks like a good summary of how to work on a branch, push it to your master, and then submit a pull request. I would just start over (your change is ultimately just one line, after all), and try to make the same change using that workflow.

**Comment by CaptainObi** [comment]
Ok got it. Thank you!

**Comment by CaptainObi** [comment]
Merging from a different branch

**Pull request closed without merging**
