### PR TITLE
1860: prohibit bankrupt company from buying train; allow repar with …

### LINKED ISSUE #4433: [1860] Unable to par a bankrupt company below normal limit with low cash
**What's your Game ID?** 

ID 29907

https://18xx.games/game/29907

**How to Reproduce the Bug?**

What steps cause the unexpected behaviour?

I sold all the owned SC shares to the bank, dropping the market price to 14. A second player bought three shares, then sold them, driving the SC bankrupt.
I had the fewest shares so gained priority and had £100 total cash but was unable to restart the SC for £50 a share.

A clone was made and when the SR restarted due to the bankruptcy other shares were sold taking cash in hand to £234 which allowed the restarting of the SC at all levels (40,44,47,50,52,54,56,58,60 and 62)

Please include screenshots (you can drag and drop or upload them into this issue)

image

image

**Which Browser / Platform?**
Chrome Version 88.0.4324.190 (on Desktop)
Samsung Internet version 13.2.2.4 (on mobile)

### LINKED ISSUE #4514: [1860]  Insolvency remains despite the fact company had purchased a train.
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

https://18xx.games/game/31708

- (optional) Provide a link to the specific action that t
https://18xx.games/game/31708?action=491
https://18xx.games/game/31708?action=522

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- Company BHI&R remains insolvent after purchasing 9+5 train.
- later on, despite the fact of having a 9+5 train, it leases a 9+5 train again. Due to a coincidence of having money (being floated again) it purchases a second 9+5 train and becomes solvent.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome,  89.0.4389.82

### PR DESCRIPTION
**Pull request by roseundy**
…low cash

Fixes #4433 
Fixes #4514 

Common file change: make Corporation min_price an attr_accessor instead of an attr_reader

### CODE REVIEW

**Review by michaeljb — APPROVED** [review]

**Comment by michaeljb** [comment]
In my local copy of the DB, this breaks 30 out of 754 games of 1860. Sounds like they can't be salvaged, is that right? I don't know enough about 1860 to judge that or if the code does the right new thing, but the code changes look fine to me 🙂

**Comment by roseundy** [comment]
It seems like a pretty high percentage. Can you give me the ids for some of them to spot-check?

**Comment by michaeljb** [comment]
Here's the full list of IDs:

```
[25951, 26081, 26350, 26357, 26361, 26413, 26576, 26700, 27158, 27868, 27981, 28561, 28899, 29360, 29396, 29504, 29668, 29764, 29824, 30079, 30402, 30434, 30455, 30815, 30874, 31013, 31697, 31708, 32281, 32521]
```

**Comment by roseundy** [comment]
Everything seems consistent with my changes. I think we pin them and move on.

**Review by michaeljb — APPROVED** [review]

**Pull request merged**
