### PR TITLE
Require permission checks to buy trains

### LINKED ISSUE #1619: Call out in UI when actions require another player's permission
By design, nothing prevents players from taking actions that require another player's permission (such as buying one of their privates, or one of their corporation's trains). And actions accidentally (or intentionally) taken can always be undone.

But it would be nice to call out those actions before they are taken, so that players are aware beforehand of which actions require permission, especially if they're new.

The lightest-weight solution (at least from the user's side) is probably to have a confirmation button somewhere for these actions. I'm not too concerned that it will add much of a speedbump to the UI, since there are very few actions that require other players' permission, and for the ones that do, you presumably already spent some time obtaining their permission, so what's one more button-press?

### PR DESCRIPTION
**Pull request by jenf**
This covers trains, privates and mergers

fixes #1619

Flash_opts had a bug which meant that errors wouldn't flash when buying privates, so i've had to effectively clone the flash code
Screenshot from 2021-01-08 22-35-20

### CODE REVIEW

**Comment by tobymao** [comment]
Yes, but make it a bit more dry, you defined the process_action twice, and perhaps the verbiage could be a little more concise?

'This action requires consent from x' -> Confirm ??

**Comment by tobymao** [comment]
Maybe you can make this Confirm View that takes in a message and a lambda

**Comment by jenf** [comment]
Done, one problem is if your on a mobile and buying the company you won't be focused in the right spot.

One possibility is making it a fixed position element to make it be a true dialog box

**Comment by jenf** [comment]
@yzemaze any opinions on how this should be styled?

I've made it an overlay dialog as it might be that the top bar isn't visible.

I think it'd need to be CSS based

**Comment by jenf** [comment]
Actually i'll just reuse flash with the addition of a button option.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
