### PR TITLE
Don't show "Review" button on archived games

### PR DESCRIPTION
**Pull request by daniel-sousa-me**

### CODE REVIEW

**Review by yzemaze — COMMENTED** [review]
This won’t be necessary once #3817 is merged. Archived games won’t be displayed at all afterwards.

Additionaly please note channel topic in 18xxgamesdev:
> FEATURE FREEZE IN PLACE UNTIL MARCH 1st
> Only submit bug fixes and code cleanups. If you have a critical feature please consult with @toby first.

**Comment by daniel-sousa-me** [comment]
Ah, I've been out of Slack. Clearly chose a bad time to pick up the work on 1870 :|

> Archived games won’t be displayed at all afterwards

So... Why archive them at all?

**Comment by ryandriskel** [comment]
> So... Why archive them at all?

It allows us to run statistics on them.

**Comment by tobymao** [comment]
no worries, will review and merge soon

**Comment by daniel-sousa-me** [comment]
> It allows us to run statistics on them.

You might want to check https://18xx.tools/stats ;)

It's still a wip, but I've been archiving all data there is some cool stuff backing

**Review by tobymao — APPROVED** [review]

**Pull request merged**
