### PR TITLE
[1822, 1822MX] fix London/Mexico City stub/permission rules, [core] log when consent is needed and allow multiple consenters

### LINKED ISSUE #9129: [1822MX] Mexico City Adjacent Track not reserved for Concession/minor company holders.
GameID: https://18xx.games/game/119429

Minor 20 lays hex O24 during OR3.  Hex O24 is one of the 5 unbuilt hexes next to Mexico City, which is covered by 6.9.2. which states that hexes adjacent to Mexico city may not have yellow track placed on them without the consent of the owner of the associated minor, or concession.  I am the owner of the IRM concession that points to hex O24 and would not have consented to this placement.  There did not seem to be a prompt or a restriction for this. 

Looking at the replay, there seems to be no prompt stopping this illegal tile lay.

image

image

### PR DESCRIPTION
**Pull request by michaeljb**
Previous behavior:

* stub to ensure track in hexes surrounding London/Mexico City (L/MC) connects to the city
* [1822MX] special double-dit tile ruling: if a minor/major other than Mexican Central Railway (MC) lays track in M22, MC's home must connect to pre-existing track

New behavior:

* per the 1822 and 1822MX rules, the minor or major on a L/MC edge has track rights for the adjacent hex, meaning they must approve any track laid there, even if it doesn't connect to L/MC
* if the minor/major has no owner, only then do the normal stub restriction apply, and track must connect to L/MC
* the special double-dit ruling for M22 in 1822MX (see #7812) only applies when MC does not have an owner
* when any action requires consent from another player (L/MC track lays, cross-buying a train from another player, etc), the log will show that the active player confirmed receiving consent

Details:

* allow tile blockers to be `hidden` by configuration for `blocks_hexes` and `blocks_hexes_consent` abilities; use this option for the 1822/MX minors, majors, and concessions which have track rights
* `hex_blocked_by_ability?` now takes the tile being laid as a parameter; in 1822MX, builder cubes (represented by a "BC" tile) are not blocked * `tile` defaults to `nil`, so other calls to the method do not need updating, but the definitions in other games still do
* `G1822::Game` no longer includes `StubsAreRestricted`, instead implementing the same methods (`legal_tile_rotation?` and `legal_if_stubbed?`) but only enforcing the stubs when the minor/major who controls the hex has no player owner
* remove the `blocks_hexes_consent` ability when a tile is being laid; per the rules, once a tile is laid, no further consent is needed from the track rights holder
* [1822MX] move special logic for MC and M22 into the `Game` class instead of duplicating it in the `Track` and `SpecialTrack` steps
* [1822] for Minor 14, add `blocks_hexes_consent` ability after it places its initial token; add logic for multiple consenters--either one of Minor 14 and whichever minor/major it shares an edge with can approve a track lay in the hex, they do not both need to
* consent logging * add new `Log` action that is subclass of `Message` to exclude it from certain checks looking for `Message` actions, e.g., `Message` actions cannot be undone, but `Log` actions can * `check_consent` now takes the acting entity as the first argument so that the active player can be the sender on the log message

Rules references:

* 1822 - 6.1.5, 7.1.5
* 1822MX - 6.9.2

Fixes #9129, tweaks #7812

-----

### 1822:

[Sample game](https://gist.github.com/michaeljb/40eb844965d5a9fc6daa8111dc80af1f)

Minor 16 lays a tile across the hex north of London; the owner of either Minor 14 or the LNWR can grant permission

1822 consent

1822 log

1822 map

### 1822MX:

[Sample game](https://gist.github.com/michaeljb/6c884c8054a9fbb627d47af8b3454921)

Minor 18 lays a tile in the hex southeast of Mexico City with consent from the IRM's owner.

1822MX log

1822MX map

### CODE REVIEW

**Comment by waaayback** [comment]
Thanks for fixing this!  Any idea when this will be pushed to the site?  We have a game of 1822MX which just ran into this issue.  We'd prefer NOT to restart the game - it has significant implications for the FNM owner.

**Review by tobymao — APPROVED** [review]

**Comment by michaeljb** [comment]
@waaayback now that this has been approved (thanks @tobymao!) I'll get it deployed this evening

**Comment by michaeljb** [comment]
@waaayback ended up being a few hours later than anticipated, but this fix is live now 🙂

**Comment by waaayback** [comment]
Thanks all for fixing this! Our game continues :)

**Pull request merged**
