### PR TITLE
18 Los Angeles - snake order for draft, priority order for stock rounds

### PR DESCRIPTION
**Pull request by michaeljb**
also a couple of small fixes:

- allowed to pass on first turn of draft
- log removed private companies

### CODE REVIEW

**Comment by michaeljb** [comment]
Hmm this broke tests, will reopen in fixed

**Comment by michaeljb** [comment]
fixed

**Comment by tobymao** [comment]
conflit

**Comment by michaeljb** [comment]
@tobymao conflict is fixed

**Pull request merged**
