### PR TITLE
Add blocks K4 to Takamatsu E-Railroad private description

### PR DESCRIPTION
**Pull request by adamranderson**
#135

### CODE REVIEW

**Comment by adamranderson** [comment]
Sure thing. Btw how can I run the linters locally?

**Comment by dfannius** [comment]
`docker-compose run rack rake`

**Comment by tobymao** [comment]
follow setup here

https://github.com/tobymao/18xx/blob/master/DEVELOPMENT.md

**Comment by adamranderson** [comment]
Thanks, fixed.

**Pull request merged**
