### PR TITLE
18scan early build

### PR DESCRIPTION
**Pull request by philcampeau**
Skeleton framework for 18Scan.

### CODE REVIEW

**Comment by tobymao** [comment]
did you code this?

**Comment by philcampeau** [comment]
Yes. Still early in the process.

**Comment by tobymao** [comment]
it looks like you just copied and pasted stuff from 1860, i'd rather things not be just copied and pasted

**Comment by philcampeau** [comment]
The only element I copied from 1860 was the opening auction code, since it works the same way. It still needs to be tweaked too.

**Comment by tobymao** [comment]
code should never be copied, if it's truly the same, it should be modularized, perhaps @roseundy can help you, or if you want to just submit this PR as the config I'll accept that.

**Comment by philcampeau** [comment]
Sure I can do it that way if it’s better.

**Pull request closed without merging**
