### PR TITLE
Update about.rb

### PR DESCRIPTION
**Pull request by ChrisTheCat**

### CODE REVIEW

**Comment by jenf** [comment]
Please fix rubocop errors

**Comment by ChrisTheCat** [comment]
I'm not sure what a rubocop error is or how to fix it. All I see is a yellow message "some checks haven't completed yet"

**Comment by jenf** [comment]
Do 'docker-compose exec rack rubocop -a'

**Comment by magnusfalt** [comment]
Best way is to do as Jen says, if you dont have the whole enviorment set up the problem with RuboCop is:

Offenses:

assets/app/view/about.rb:20:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.
assets/app/view/about.rb:27:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.
assets/app/view/about.rb:29:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.
assets/app/view/about.rb:35:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

You are ending thoose line with a space. If you do RuboCop will complain.

**Comment by ChrisTheCat** [comment]
I don't have a docker (or a clocker or a rocker) nor can I run commands. I
just use the github web interface and click buttons and type stuff :-)

I'll see if I can find the trailing whitespace and remove it.

**Comment by ChrisTheCat** [comment]
OK, I figured out how to reopen the file. Those were all blank lines... but
at any rate, I deleted the offending lines, so maybe that fixed it? Not
sure how to re-commit or re-pull it.

**Comment by ChrisTheCat** [comment]
Sigh, I got another error. I should just tell someone what edits I want
made in future...

[image: Screen Shot 2021-03-16 at 7.12.23 AM.png]

**Comment by ChrisTheCat** [comment]
Here's the error message I see. I was 99% sure I removed the trailing whitespace - I deleted the entire offending line, put the cursor at the end of the previous line, pressed enter, and never pressed the space bar. I'm at a loss what to do now.

Screen Shot 2021-03-16 at 7 15 34 AM

**Comment by dfannius** [comment]
The editor is probably "helpfully" inserting whitespace automatically when you press enter, to make it easy to line things up. I imagine the whitespace has to be deleted by actually deleting it manually and not relying on the enter key.

**Comment by ChrisTheCat** [comment]
woo hoo, looks like it worked this time.

**Pull request merged**
