### PR TITLE
Walk get all paths

### PR DESCRIPTION
**Pull request by ventusignis**
Before, `Node.path ` would yield all path segments reachable from a node. Now it also yields all possible paths (visited paths and visited edges)

### CODE REVIEW

**Comment by michaeljb** [comment]
Looks like the merge conflict is just a comment, should be easy to resolve.

**Comment by michaeljb** [comment]
Does this spot need updating with the visited and paths and visited edges?

https://github.com/tobymao/18xx/blob/2a8ff3ef5f0d70ec93cd827a6b05857a657f777c/lib/engine/graph.rb#L158

**Comment by tobymao** [comment]
this needs a rebase

**Comment by tobymao** [comment]
closing for now, can reopen when you're ready

**Pull request closed without merging**
