### PR TITLE
Revert "18ZOO - Update 2D StockMarket to show bigger cells when there is any user_info in any cell"

### PR DESCRIPTION
**Pull request by crericha**
Reverts tobymao/18xx#9790

### CODE REVIEW

**Comment by crericha** [comment]
@carlorusso the stock market change broke many games. I am reverting the change for now. Please test with games listed in this issue - #9809 before reposting the change in a PR. Thanks!

**Comment by tobymao** [comment]
i had already reverted this https://github.com/tobymao/18xx/pull/9773, it didn't seem like a safe change cc @michaeljb

**Review by tobymao — APPROVED** [review]

**Comment by tobymao** [comment]
don't bring in these 18zoo changes

**Comment by carlorusso1984** [comment]
> @carlorusso the stock market change broke many games. I am reverting the change for now. Please test with games listed in these issues - #9809, #9810, and #9811 before reposting the change in a PR. Thanks!

ok, I'll do.
I didn't expect any changes in any other game, because from the code I cannot find any reference to user info in other games.

**Pull request merged**
