### PR TITLE
Opal 1.6.1 (longer stack traces!), and update other gems

### PR DESCRIPTION
**Pull request by michaeljb**
[Opal 1.6 stops truncating stacktraces at 15 lines, and should have some performance improvements](https://github.com/opal/opal/blob/master/CHANGELOG.md#160---2022-11-24), but it required a few unexpected changes:
* when snabbdom is loaded in `public/assets/server.js`, it did not successfully set `window.snabbdom` until I forked snabberb (at v1.5.4) and added [this commit](https://github.com/tobymao/snabberb/commit/67e7dc3b14e6831ab4027337d323a6848a9f390e)
* `assets/app/view/game/part/town_dot.rb` - `nil` in a component's children array throws an error instead of just plopping `undefined` on the DOM; that had to be fixed for `town_dot.rb`. I opened a few other games in progress to see if they had problematic elements but haven't found any, but upon release we may find more instances of this
* `assets/deps.rb` - changing the order of the imports changes the order they end up appearing in `public/assets/server.js`, and without the change here, `message-bus-ajax.js` threw its error about needing MessageBus to be loaded first

Many gems were upgraded to the version provided by `bundle update`, a few were not:

* Opal to 1.6.1, not 1.7
    * with 1.7 there is an error in the prerendered script, it appears to be in a `store()` call within a snabberb component but I could not figure out more specifically where the error was
* mini_racer to 0.6.3
    * 0.6.4, 0.7, and 0.8 change which Node version is targeted ([mini_racer CHANGELOG](https://github.com/rubyjs/mini_racer/blob/main/CHANGELOG)), leading to errors I didn't have any idea of how to debug from the console output
* did not upgrade rubocop - many new cops to configure and/or change the code for

### Before clicking "Create"

- [x] Branch is derived from the latest `master`
- [x] Add the `pins` label if this change will break existing games
- [x] Code passes linter with `docker compose exec rack rubocop -a`
- [x] Tests pass cleanly with `docker compose exec rack rake`

### CODE REVIEW

**Comment by michaeljb** [comment]
> * when snabbdom is loaded in public/assets/server.js, it did not successfully set window.snabbdom until I forked snabberb (at v1.5.4) and added [this commit](https://github.com/tobymao/snabberb/commit/67e7dc3b14e6831ab4027337d323a6848a9f390e)

@tobymao - would you have any ideas for handing the snabberb/snabbdom problem that's less hackish than this? I imagine it should be possible to preserve the logic for checking for `module.exports` or `define`.

Without it, in the browser you just get `ReferenceError: snabbdom is not defined`, and here's the error in the docker console output ([server.js in this gist](https://gist.github.com/michaeljb/8e47f8dc4fa86462d66e8d2e0c92a21a)):

```
rack_1   | E,
[2023-09-03T23:30:51.116478 #23] ERROR -- :
["JavaScript at <anonymous>:52929:23",
"JavaScript at <anonymous>:53235:7",
"JavaScript at Opal.modules.snabberb/component (<anonymous>:53245:5)",
"JavaScript at Object.Opal.load_normalized (<anonymous>:2692:20)",
"JavaScript at Object.Opal.require (<anonymous>:2731:17)",
"JavaScript at klass.$$require (<anonymous>:15095:19)",
"JavaScript at Opal.modules.snabberb (<anonymous>:50673:8)",
"JavaScript at Object.Opal.load_normalized (<anonymous>:2692:20)",
"JavaScript at Object.Opal.require (<anonymous>:2731:17)",
"JavaScript at klass.$$require (<anonymous>:15095:19)",
"JavaScript at <anonymous>:53375:8",
"JavaScript at Object.Opal.queue (<anonymous>:2805:17)",
"JavaScript at <anonymous>:53367:6",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:228:in `eval_unsafe'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:228:in `block (2 levels) in eval'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:348:in `timeout'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:227:in `block in eval'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:225:in `synchronize'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:225:in `eval'",
"/usr/local/bundle/gems/mini_racer-0.6.3/lib/mini_racer.rb:429:in `initialize'",
"/18xx/lib/js_context.rb:8:in `new'",
"/18xx/lib/js_context.rb:8:in `initialize'",
"/18xx/lib/assets.rb:32:in `new'",
"/18xx/lib/assets.rb:32:in `context'",
"/18xx/api.rb:195:in `render'",
"/18xx/api.rb:173:in `render_with_games'",
"/18xx/api.rb:104:in `block (2 levels) in <class:Api>'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda/request.rb:536:in `always'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda/request.rb:368:in `root'",
"/18xx/api.rb:103:in `block in <class:Api>'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda.rb:518:in `_roda_run_main_route'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda/plugins/_before_hook.rb:27:in `_roda_run_main_route'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda.rb:496:in `block in _roda_handle_main_route'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda.rb:494:in `catch'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda.rb:494:in `_roda_handle_main_route'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda/plugins/error_handler.rb:88:in `_roda_handle_main_route'",
"/usr/local/bundle/gems/roda-3.71.0/lib/roda.rb:380:in `block in base_rack_app_callable'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/deflater.rb:47:in `call'",
"/usr/local/bundle/gems/message_bus-4.3.8/lib/message_bus/rack/middleware.rb:60:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/tempfile_reaper.rb:20:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/lint.rb:63:in `response'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/lint.rb:35:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/show_exceptions.rb:27:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/common_logger.rb:43:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/chunked.rb:102:in `call'",
"/usr/local/bundle/gems/rack-3.0.8/lib/rack/content_length.rb:20:in `call'",
"/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:634:in `process_client'",
"/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:739:in `worker_loop'",
"/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'",
"/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:143:in `start'",
"/usr/local/bundle/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'",
"/usr/local/bundle/bin/unicorn:25:in `load'",
"/usr/local/bundle/bin/unicorn:25:in `<main>'"
]

rack_1   | E,
[2023-09-03T23:30:51.116650 #23] ERROR -- : ReferenceError: snabbdom is not defined
```

**Comment by tobymao** [comment]
make a pr for snabbdom?

**Comment by tobymao** [comment]
@michaeljb maybe you need to rebuild snabbdom with the latest tooling

**Comment by michaeljb** [comment]
The part I edited is generated by browserify, from `browserify build.js -p esmify -s snabbdom > opal/vendor/snabbdom.js` (taken from the comment in snabberb's `build.js`). I've tried editing some different things but haven't figured much more out. Going to compare the generated `deps.js` files with Opal 1.5 vs 1.6, maybe there are some new config options or something I can add to the Opal builder.

**Comment by michaeljb** [comment]
Backing out the bump to Ruby 3.2 since any new features in 3.2 are not supported until Opal 1.7

**Comment by michaeljb** [comment]
A couple notes from the slack conversation
- my above linked change to snabbdom.js is a hand edit of output from browserify
-  it works with Opal 1.5.1, but not 1.6.0, so it seems like something in Opal’s changes broke it
- might be worth trying to come up with a trivial example to demonstrate the breakage

**Comment by michaeljb** [comment]
>     * `assets/deps.rb` - changing the order of the imports changes the order they end up appearing in `public/assets/server.js`, and without the change here, `message-bus-ajax.js` threw its error about needing MessageBus to be loaded first

Pretty sure now changing the order working at all has been a coincidence, this is probably [opal #2505](https://www.github.com/opal/opal/issues/2505), and I need to just set `OPAL_PREFORK_DISABLE=true`.

**Comment by michaeljb** [comment]
Closing this in favor of #9557, I would overwrite this PR but I don't understand why the builds in the github workflow are taking forever, maybe this branch is just cursed.

**Pull request closed without merging**
