### PR TITLE
18usa: stock value movement, metropolitian cities, offboards

### PR DESCRIPTION
**Pull request by CaptainObi**
First round of changes for 18USA. I've fixed the offboard randomization, added metropolitan randomization, and added the different stock value movement. I've also moved it to the new structure.

### CODE REVIEW

**Comment by CaptainObi** [comment]
(I'm not sure what this bug is, could I get some insight? @ventusignis )

**Comment by magnusfalt** [comment]
In lib/engine/game/g_18_usa/step/loan.rb the name is of the module is 1817, i think you overrides the normal 1817 module and then all the rspec for 1817 will fail.

**Comment by CaptainObi** [comment]
That sounds right

**Comment by CaptainObi** [comment]
I'm clearly doing something wrong. I'm going to redo this whole mess.

**Comment by magnusfalt** [comment]
A good idea is to run "docker-compose exec rack rake" on your machine before you commit. Then you can fix the rubocop errors before it hits github.

**Comment by CaptainObi** [comment]
> docker-compose exec rack rake

I did, but it clearly didn't work.

**Pull request closed without merging**
