### PR TITLE
18usa: Map and Offboards

### PR DESCRIPTION
**Pull request by CaptainObi**
Added config for 18USA map, and set up the off board randomization.

### CODE REVIEW

**Comment by tobymao** [comment]
who's going to work on 18usa?

**Comment by CaptainObi** [comment]
@tobymao I plan to implement private randomization, metropolis randomization, and the Pullmans, from there I will take a look at implementing some of the privates. I don't think I will be able to finish the game but I could get it pretty far.

**Comment by ventusignis** [comment]
I can help get it over the finish line

**Comment by tobymao** [comment]
clean up the tokens

**Review by tobymao — APPROVED** [review]

**Pull request merged**
