### PR TITLE
Fix unable to lay coal in hex B8 from a Brown Dawson City

### PR DESCRIPTION
**Pull request by ventusignis**

### CODE REVIEW

**Comment by jenf** [comment]
Please provide a sample game so I can validate.

**Comment by ventusignis** [comment]
Here is a clone of the game I had yesterday where we hit it
https://gist.github.com/ventusignis/92a87978cddd74af42595bafae90bf0f

**Comment by ventusignis** [comment]
`.edges()` returns the edges of the tile, as it is in the tile manifest while `.exits()` returns the rotated exits; This never came up in 1817 because all of the K cities near mountains face up and the other cities are spiders or Boston (which lucks out?)

**Comment by jenf** [comment]
code looks just running to check no regressions on existing 1817 games now

**Review by jenf — APPROVED** [review]

**Pull request merged**
