### PR TITLE
Optionally play a sound on change of active player

### PR DESCRIPTION
**Pull request by mavit**
Addresses #1638.

Caveats:
- The sound effect that plays when it is another player’s turn was intended as a placeholder for testing, but I grew to like it so I’ve left it in for now.  Nevertheless, we might want to replace it with something less intrusive, disable it by default, or even remove it entirely.
- The sounds do not play immediately if you happen to be reviewing the game history when another player takes their turn.
- I’ve never used Opal before and have barely used Ruby, so, when reviewing, please imagine that meme of the Labrador doing chemistry.

### CODE REVIEW

**Comment by bridger15** [comment]
If it is not already build this way, I suggest a specific, more obvious/attention grabbing sound for when it is your own turn, and a less obvious (quieter?) sound when play passes to another player.

**Comment by mavit** [comment]
> If it is not already build this way, I suggest a specific, more obvious/attention grabbing sound for when it is your own turn, and a less obvious (quieter?) sound when play passes to another player.

Agreed.  For the other player sound I had in mind the “ker-chunk ker-chunk” noise of a train as it moves along the rails, but I’m not sure where to find such as sound isolated from background noise.

**Comment by tobymao** [comment]
closing for now

**Comment by mavit** [comment]
> closing for now

May I ask why?

**Comment by bridger15** [comment]
> > closing for now
> 
> May I ask why?

I'd also like to know.  This is a super useful feature for everybody playing live and I still don't understand what's taking so long to make it happen.  Should we make a bigger stink about it? Slip some $20s under the door? :P

**Comment by dfannius** [comment]
> I still don't understand what's taking so long to make it happen.

It has not been a priority for anyone who is spending their free time contributing to the site. PRs are always welcome, of course.

> Should we make a bigger stink about it?

No.

**Pull request closed without merging**
