### PR TITLE
18CZ Added Restrictions for stubs

### PR DESCRIPTION
**Pull request by Zwergenpunk**
@jenf Is that all thats needed? It was all I found in 1867

### CODE REVIEW

**Comment by jenf** [comment]
Yeah, can we do it as an module include since we've got it three times now

**Comment by Zwergenpunk** [comment]
like the `CompanyPriceUpToFace` ? 

Yeah that sounds reasonable

**Comment by Zwergenpunk** [comment]
I'm not sure about the naming of the module. If someone has a better name. I'm fine with that ;)

Should I add it to 1867 myself? I don't want to break anything I don't know :/

**Comment by jenf** [comment]
I would, same with 18 la

**Comment by Zwergenpunk** [comment]
I changed 18LA and 1867.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
