### PR TITLE
light corp bg color => black text

### PR DESCRIPTION
**Pull request by yzemaze**
Stumbled upon 1828 and changed other ones that made me squint as well.
[We could get rid of this config option altogether and just rely on contrast_on.]

ante
image

post
image

### CODE REVIEW

**Comment by ventusignis** [comment]
Would you mind updating the text color for the Plant svg in `public/logos/18_fl/Plant.svg` to match?

**Comment by yzemaze** [comment]
@ventusignis 
Check files changed ;-)

**Comment by ventusignis** [comment]
Thanks!

**Comment by scottredracecar** [comment]
Fantastic idea

**Review by tobymao — APPROVED** [review]

**Comment by yzemaze** [comment]
> Fantastic idea

What exactly?

**Pull request merged**
