### PR TITLE
The Old Prince: 1871 into alpha

### PR DESCRIPTION
**Pull request by kelsin**
This sets 1871 to alpha status and has a few other things:

1. Corrects 4+ train bugs
2. Auto passes and offers in auction when applicable
3. Adds some tests for the tranch code

I will be testing everything more tomorrow with Lucas so please don't merge quite yet, but we can code review.

### CODE REVIEW

**Comment by kelsin** [comment]
Running a test on Sunday at 2pm PST, after that I'll ask Toby to merge if I can solve all bugs found. Also will be adding docs for the consent blocking ability in this PR by then too.

**Comment by philcampeau** [comment]
Let's go kelsin!

**Comment by kelsin** [comment]
> Let's go kelsin!

We have one more bug we'll be fixing before alpha, and I'm sure some more after, but should have it ready to merge tomorrow morning with Lucas's approval if I fix that bug.

**Comment by dfannius** [comment]
Will there be a link to the rules before the title goes into alpha?

**Review by tobymao — APPROVED** [review]

**Comment by kelsin** [comment]
> Will there be a link to the rules before the title goes into alpha?

Just added it, not deploy yet: https://s3.amazonaws.com/public.valefor.com/TOP71_RULES_PROTOTYPE.pdf but will be soon, already merged.

**Pull request merged**
