### PR TITLE
Fix buy_share to handle preferred shares with bundles correctly

### LINKED ISSUE #7787: [Harzbahn 1873] Game stuck in loading loop forever
Hi,

Game 78782 won't load - it just sits in "Loading game..." forever.  Is there any way to rescue this game?

Thanks,
Eric

https://18xx.games/game/78782

### PR DESCRIPTION
**Pull request by roseundy**
Fixes #7787

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Comment by tobymao** [comment]
wait a second, why would share not have the preferred method?

**Review by tobymao — CHANGES_REQUESTED** [review]
something is fishy here

**Comment by roseundy** [comment]
Because share could be a bundle, which doesn't have that method.

**Comment by tobymao** [comment]
can it have that method?

**Comment by roseundy** [comment]
The bug is that Button::BuyShare was modified to handle preferred shares without recognizing that bundles can also be bought.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
