### PR TITLE
[1860] add direct link to rules pdf

### PR DESCRIPTION
**Pull request by benjaminxscott**
Previously the rules link was to BGG, which requires login to view the PDF

This is on my personal dropbox as a shared file, can change to something else if we want

### CODE REVIEW

**Review by roseundy — COMMENTED** [review]
Can we move this to a location on github? I don't think pointing to a personal Dropbox location is a good idea.

Under 18xx/public (like 18xx/public/rules) would work.

**Comment by benjaminxscott** [comment]
Added a link to the eventual 'raw hosting' link on master

**Comment by roseundy** [comment]
Sorry about that, but Toby would prefer your original solution. He doesn't want copyrighted material on github. So your original commit was fine :-/

**Comment by benjaminxscott** [comment]
blew away the history just in case

**Pull request merged**
