### PR TITLE
[18Rhl] Implement RhE bonus when link exists Aachen-Duren-Cologne

### PR DESCRIPTION
**Pull request by perwestling**
Also add a reference game.

### CODE REVIEW

**Review by tobymao — COMMENTED** [review]
you need to keep the return if loading since connection check hits graph, you need to use auto actions

**Comment by perwestling** [comment]
@tobymao If I keep the "return if loading" this breaks the code. 

What happens is that RhE lays the last tile that satifies the bonus, the check returns without checking the bonus, and now the corproation does not have money to do a token - so the game is out of synch.  It fails on action 201.

I am not sure how to solve this - can I get it to wait until graph has been loaded? 
What do you mean by auto action?

It need to take place between lay tile action and token action.

**Comment by tobymao** [comment]
There’s a concept of auto actions for this use case, where you persist an
action so that you don’t need to check the graph. See 1870 destination as
an example.

**Comment by perwestling** [comment]
Ok, I will check it out.

**Comment by perwestling** [comment]
@tobymao Have now made an attempt. It is not perfect, as it does not do the check directly after the tile lay, so it wont give RhE the money direct after it creates the link, but at least it gives close to the required. RhE will have to wait until next OR to spend the money.

**Comment by tobymao** [comment]
why not do it correctly?

**Review by tobymao — APPROVED** [review]

**Pull request merged**
