### PR TITLE
Removed a visual error with limited train buying in 18AL (fixes #1625) 

### LINKED ISSUE #1625: 18AL: Misleading label on info screen
On the Info screen for 18AL, Phase 4 is labeled with "Limited Train Buy".  However, the rules (and the implementation) specifically permit multiple buys as soon as the first 4 train is bought. (4.2.5.f)

### PR DESCRIPTION
**Pull request by CaptainObi**
Removed the visual error. This was just done in config and does not affect game play.

### CODE REVIEW

**Comment by dfannius** [comment]
Looks much nicer than the last PR :)

**Comment by yzemaze** [comment]
… and you could earn a bonus point by putting "fixes #x" in the description, cf. https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by CaptainObi** [comment]
I thought title was fine

**Comment by perwestling** [comment]
Looks good, @CaptainObi 
I think you need to put Fixes #1625 in the description to create the link to the issue, as per the link yzemaze gave above. We'll see if this comment creates the link?

**Comment by perwestling** [comment]
I think that if one creates that link, the issue will be closed automatically. Now we might have to do it manually.

**Comment by perwestling** [comment]
Ah, did close it automatically - great.

**Pull request merged**
