### PR TITLE
chat: disallow empty messages

### PR DESCRIPTION
**Pull request by bsnyder788**

### CODE REVIEW

**Comment by tobymao** [comment]
you'll have to fix the build you can take it locally with

docker-compose exec rack rake

**Comment by bsnyder788** [comment]
Hmm, I checked out the latest commit to master prior to my commit and the exact same tests fail so I think its just master that is broken possibly?

```Failed examples:

rspec './spec/lib/engine/games/g_18_chesapeake_spec.rb[1:1:1]' # Engine::Game::G18Chesapeake full game 1157 matches result exactly
rspec './spec/lib/engine/games/g_18_chesapeake_spec.rb[1:1:2]' # Engine::Game::G18Chesapeake full game 1191 matches result exactly
rspec './spec/lib/engine/games/g_18_chesapeake_spec.rb[1:1:3]' # Engine::Game::G18Chesapeake full game 1228 matches result exactly

/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-support-3.9.2/lib:/usr/local/bundle/gems/rspec-core-3.9.1/lib /usr/local/bundle/gems/rspec-core-3.9.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
[bsnyder@neptune:~/code/18xx on 01a5520]
```

**Comment by tobymao** [comment]
your right i forgot!

**Comment by sparr** [comment]
Put if you put "resolves #525" in the description of the PR, it will get linked to the issue automatically without you needing to have posted a link there, and the issue would have closed when this merged.

**Pull request merged**
