### PR TITLE
1856: Waterloo cannot be used outside of a corporation's OR now

### LINKED ISSUE #5627: 1856 Waterloo & Saugeen can be (incorrectly) be used in SR
https://18xx.games/game/44700?action=183#tools

### PR DESCRIPTION
**Pull request by ventusignis**
Fixes #5627

### CODE REVIEW

**Review by jenf — APPROVED** [review]

**Comment by jenf** [comment]
This might cause a lot of games to be archived, can someone check the database?

**Review by jenf — CHANGES_REQUESTED** [review]
please run the validation script on, so we know if we need a migration or not.

I think 'track' forces an option to buy corporations

**Comment by ventusignis** [comment]
If this will cause such wide archiving, is there a way for me to make a migration script to mitigate this assuming people aren't abusing this private?

**Comment by ventusignis** [comment]
Also the fix for #5639 when I'm able to put that together will surely cause archiving so maybe merging this should be delayed until it can be batched with other archiving PRs come up?

**Pull request merged**
