### PR TITLE
Initial commit for 18xx.game's 1828 implementation.

### PR DESCRIPTION
**Pull request by crericha**

### CODE REVIEW

**Comment by tobymao** [comment]
you need to add an override for title or change the class names

**Comment by crericha** [comment]
I'm interested in your thoughts here. My current thoughts o the topic is use the wiki for the full name, reference to JC and 1828, and have a rules section listing the visual and naming differences that matter when reading the rulebook and a link to the 1828 rulebook. Then on the site for the game dropdown list and source files, we'd use the shortened name of 1828.. The rationale is I don't think we'd list 1830 as 1830: Railways & Robber Barons, so its okay to use the short name there.

**Comment by tobymao** [comment]
i don't want  there to be any confusion, as we do this for the 1846 2 player variant

**Comment by crericha** [comment]
Changed name to 1828.Games and added implementer note to address.

**Comment by crericha** [comment]
Heads up that I already had a couple of other commits ready to go, so they are included here too.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
