### PR TITLE
Improvement for 18AL, 18GA, 18AL (#961)

### PR DESCRIPTION
**Pull request by perwestling**
- Implement "max 1 train from depot before phase 4" for all three
- Correct operation round count for 18AL and 18TN

### CODE REVIEW

**Comment by perwestling** [comment]
The "max 1 train from depot before phase 4" contains exactly the same implementation. So question is if this should be generalized so that all three uses one and same implementation?

**Comment by tobymao** [comment]
this is using the old style of operating round and mostly copy and paste, for now, please remove all of those changes and only keep the config changes

**Comment by perwestling** [comment]
@tobymao: Without "operating_rounds" lines in 18AL I encountered a bug in OR1: After the last company has bought its train, and then Skip buying more, the game got "stuck". It did not switch to SR2.
I describes the problem in #961. 

If I add the "operating_rounds" that problem disappeared.

But I will try to update my commit.

A question: What do you think about the operation - should I generalize it to make one ruby file for handling the operation round feature of just allowing one buy before phase 4, or is it OK with 3 files that are essentially the same?

**Comment by tobymao** [comment]
@perwestling i'm currently rewriting the operating rounds to make it easier to do things like you want

3 files the same is not ok, and working on this now in the "old way of doing things" will make it more difficult for me to complete my rewrite

**Comment by perwestling** [comment]
@tobymao: OK, I can wait for the rewrite before trying to implement this feature. I will close this pull-request and make a new one further on.

**Comment by tobymao** [comment]
Are you in the 18xx slack? It will be more efficient to communicate there.

https://join.slack.com/t/18xxgames/shared_invite/zt-8ksy028m-CSZC~G5QtiFv60_jdqqulQ

**Pull request closed without merging**
