### PR TITLE
Use buttons instead of links for the activated abilities

### PR DESCRIPTION
**Pull request by daniel-sousa-me**
Most new users get confused with the links. This should help

image

### CODE REVIEW

**Comment by jenf** [comment]
Code changes themselves looks good, but it's probably good to get a second opinion on the change to the UI.

**Comment by michaeljb** [comment]
I am a fan of this change, however in my quick test, clicking on one company showed its text but did not make the button look different the way @daniel-sousa-me's screenshot does :thinking: 

Screenshot from 2020-12-04 10-22-55

**Comment by daniel-sousa-me** [comment]
Which browser+OS?

**Comment by daniel-sousa-me** [comment]
This is using the CSS. Maybe you need to do Ctrl+Alt+R?

**Comment by michaeljb** [comment]
Ubuntu 18, Firefox 83

I do see the button element does have `class="active"`...

I also see in the CSS, the `button.active` definition is under `@media(hover: hover) and (pointer: fine) {`. I don't know exactly what `@media` does, good it be activating the class only when the element is actually being hovered?

**Comment by michaeljb** [comment]
Rebuilding the container did the trick :slightly_smiling_face:

**Review by michaeljb — APPROVED** [review]

**Comment by daniel-sousa-me** [comment]
I didn't notice the @media there. It is meant to prevent the :hover effects in devices where they don't make sense (like smartphones).

I'll update the CSS

**Pull request merged**
