### PR TITLE
1870: Take train distance into account when checking for connection

### PR DESCRIPTION
**Pull request by daniel-sousa-me**
I couldn't find a way to do this without modifying walk. I hope this is ok.

### CODE REVIEW

**Comment by tobymao** [comment]
fix lint

**Comment by magnusfalt** [comment]
Ive been working on refactoring the node.walk to handle 1822 enormous walk tree. I can incorporate you max_nodes, but im closing this until ive verified all my refactoring is working. You can then open an new PR with max_nodes.

**Comment by daniel-sousa-me** [comment]
@magnusfalt @tobymao 
It's been a week. Is there any eta on this?

**Comment by tobymao** [comment]
refactoring just finished, max_nodes got lost in the shuffle

**Comment by daniel-sousa-me** [comment]
Oops, I had missed it. No problem, I'll reopen the PR. Thanks

**Pull request closed without merging**
