### PR TITLE
1870: Fixed error on migration (fixes #4600 again)

### LINKED ISSUE #4600: [1870] At end of SR, company share should increase if shares fully sold (which includes shares redeemed by the company) - Rule Error
**What's your Game ID?**

https://18xx.games/game/33080

It is the end of SR2. MP is fully sold (9 shares in players hands one share in company treasury). At the end of the SR2, the share price does not go up one row on the stock chart as it should.

To quote from page 14 of the rules

"At this time, share value tokens of companies that have all their shares in the hands of players or companies are adjusted up one row".

Share Price doesn't jump when shares fully sold

### PR DESCRIPTION
**Pull request by daniel-sousa-me**

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Review by tobymao — APPROVED** [review]

**Comment by tobymao** [comment]
conflict

**Comment by daniel-sousa-me** [comment]
Rebased

**Comment by jenf** [comment]
More conflicts. Please could you mention if the PR requires games to be archived/pinned

**Comment by daniel-sousa-me** [comment]
I'm sorry, I thought the check was automatic. But basically all the PRs I've been opening have the potential to delete some games. This one in particular will delete most games that have passed SR2/3.

I've rebased again. Since this is deleting the fixture, I think it will come into conflict with any other commit that is made in between.

**Comment by jenf** [comment]
nope, we put it on manually

**Comment by michaeljb** [comment]
pinned 32980

**Pull request merged**
