### PR TITLE
Cache stop calculation for routes

### PR DESCRIPTION
**Pull request by dfannius**

### CODE REVIEW

**Comment by tobymao** [comment]
let's change this be caching style

def stops
@stops ||= begin do
...
end
end

and then when you want to clear the cache, just do @stops = nil

**Comment by dfannius** [comment]
Do you really mean Stops with a capital s? That doesn't look like the usual style. (And if not, then is there a conflict between the @stops variable and the stops method?

**Comment by tobymao** [comment]
no, just @stops, and there's no conflict, stops is the method, @stops is the instance variable

**Comment by dfannius** [comment]
I'm changing it to that style on the branch that implements "smart stops", so I'm going to submit it as part of that PR rather than doing this separately here and then rebasing.

**Pull request closed without merging**
