### PR TITLE
18MS: Add line to P1/P2 description about OR 1 buy-in.

### PR DESCRIPTION
**Pull request by perwestling**
It seems some players do forget to use this feature so adding it
should hopefully work as a reminder.

### CODE REVIEW

**Comment by perwestling** [comment]
@scottredracecar The added lines are not in the physical game. I think it might be a good idea as players seem to miss out on that possibility. Also I am wondering about the "Major Company". The 18xx.games uses corporation for "major company" but the descriptions of the privates do use the same text in the physical game. So I used "Major Company" in the added text as well.

So do you think this is OK?

With this PR handled, the rules link updated, then I think we can add a PR to make 18MS production state.

**Comment by perwestling** [comment]
I sent a question about it to Mark Derrick as well.

**Comment by tobymao** [comment]
you shouldn't use the word major company, call it a corporation

**Comment by perwestling** [comment]
@tobymao Got thumbs up from designer so I have now made it consistent according to 18xx.games standard.
Also updated 18MEX in the same style.  18AL/18GA/18TN were all ok.

**Review by tobymao — APPROVED** [review]

**Pull request merged**
