### PR TITLE
add dashes to tokens to be color blind friendly

### PR DESCRIPTION
**Pull request by zeitlinger**
add dashes to tokens to be color blind friendly

image

### CODE REVIEW

**Comment by roseundy** [comment]
How does this play with with token highlighting?

**Comment by crericha** [comment]
> How does this play with with token highlighting?

Yeah, I can see the "spokes" being a problem. Maybe experiment with a small white or black outline between the token and the player color? Basically, some way to distinguish the player color circle instead of reshaping it.

**Comment by zeitlinger** [comment]
> How does this play with with token highlighting?

the problem (for me) is to find a set of colors that are easily distinguishable.
In [another game](https://www.boardgamers.space/boardgame/gaia-project), I've successfully used dashes (added selectively to colors that are similar for me) to make a clear distinction.

Here's a set of colors that would otherwise be difficult for me:

image

**Comment by jason-johnson** [comment]
Could this be added as a profile switch so people who need it can turn it on?

**Comment by tobymao** [comment]
closing for now

**Pull request closed without merging**
